"""add email to owners

Revision ID: c402d9d77c46
Revises: 
Create Date: 2026-10-02 19:18:22.286730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c402d9d77c46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('birth_date', sa.Date(), nullable=False))
    op.alter_column('animals', 'breed',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    op.create_index(op.f('ix_animals_name'), 'animals', ['name'], unique=False)
    op.drop_constraint(op.f('fk_owner'), 'animals', type_='foreignkey')
    op.create_foreign_key(None, 'animals', 'owners', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('animals', 'birthday')
    op.add_column('owners', sa.Column('email', sa.String(), nullable=False))
    op.alter_column('owners', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_index(op.f('ix_owners_name'), 'owners', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owners_name'), table_name='owners')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.alter_column('owners', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('owners', 'email')
    op.add_column('animals', sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'animals', type_='foreignkey')
    op.create_foreign_key(op.f('fk_owner'), 'animals', 'owners', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_animals_name'), table_name='animals')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.alter_column('animals', 'breed',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('animals', 'birth_date')
    # ### end Alembic commands ###
